development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>