# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'active_record'
require 'yaml'
require 'rdoc/task' 
require 'tasks/rails'

RDoc::Task.new do |rdoc|
  rdoc.main = 'README'
  rdoc.rdoc_dir = 'doc'
end

db_config = YAML.load_file('config/database.yml')
ActiveRecord::Base.establish_connection(db_config[ENV['RAILS_ENV'] || 'development'])