# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rdoc/task'  # Use 'rdoc/task' em vez de 'rake/rdoctask'

require 'tasks/rails'

# Se houver código relacionado ao RDocTask, substitua por RDoc::Task
RDoc::Task.new do |rdoc|
  rdoc.main = 'README'
  rdoc.rdoc_dir = 'doc'
end
